#!/bin/sh

length=${#GOPATH}
srcpath=${PWD:length}
imagesrcpath="/go"${srcpath}

echo $imagesrcpath
image="golang:1.11-alpine"

target="kubeconfig"
targetimage="kubeconfig:latest"

docker run --rm -v "${PWD}":"${imagesrcpath}" -w ${imagesrcpath} ${image} go build -o ${target}

docker build -t ${targetimage} .

