---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: workshop
data:
  TILLER_ROLE: tiller-user
  TILLER_NAMESPACE: kube-system
  NAMESPACE_PREFIX: clustar-
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ksonnet.io/component: kubeconfig
  name: kubeconfig
  namespace: workshop
spec:
  ports:
  - port: 8085
    targetPort: 8085
  selector:
    app: kubeconfig
  type: ClusterIP
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    ksonnet.io/component: kubeconfig
  name: kubeconfig
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeconfig
  template:
    metadata:
      labels:
        app: kubeconfig
    spec:
      serviceAccountName: cluster-operator
      containers:
      - image: asdfsx/kubeconfig
        name: kubeconfig
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: cluster-info
