
apiVersion: v1
kind: ConfigMap
data:
  CLUSTER_SERVER: https://172.17.255.200:8443
  CLUSTER_CA_DATA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ3akNDQXRhZ0F3SUJBZ0lVYTd5WmsvbE9JSlBDNnJzSWQ2eVlhR1A0YVh3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2ZURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFXcHBibWN4RlRBVEJnTlZCQWNUREVKbAphV3BwYm1jZ1kybDBlVEVUTUJFR0ExVUVDaE1LUzNWaVpYSnVaWFJsY3pFYk1Ca0dBMVVFQ3hNU1MzVmlaWEp1ClpYUmxjeTFoYm5OcFlteGxNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6TUI0WERURTRNRGt4T0RFd01ERXcKTUZvWERUSXpNRGt4TnpFd01ERXdNRm93ZlRFTE1Ba0dBMVVFQmhNQ1EwNHhFREFPQmdOVkJBZ1RCMEpsYVdwcApibWN4RlRBVEJnTlZCQWNUREVKbGFXcHBibWNnWTJsMGVURVRNQkVHQTFVRUNoTUtTM1ZpWlhKdVpYUmxjekViCk1Ca0dBMVVFQ3hNU1MzVmlaWEp1WlhSbGN5MWhibk5wWW14bE1STXdFUVlEVlFRREV3cHJkV0psY201bGRHVnoKTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzZ1Zla08zaVp3T2lOTkRRU0ZobApBa0s1Ui9EY1hsY3B2SXNqOG9pN1orZk05M3ZRNE1tR25aSEFYaGRKaU92bnp3OXVmYnNzVkUxZWs2eWRPMlA4CjYzSXFUY0ovVjdzVmQrckcrc1JhNm0zV05xNkpKK1N1NjhyN0xzOTU3Zlc1YU1ZMklNRlBjYi94dGZSMnVXUXoKMHZ1TU1oVGZ1cmJDZUtReE1sMWphdTNTWXQwbkpXWEVDY2ViVTdSWnh1cXRyRjB1K0RzbDNiYkNTclpydmswQQpRMUtUaW51MHUwdTdPODZ3RzZscEVnRGpQTGd6d1pyZDdzd3BBdkZrSXpmMmUxWWwvZzdaQ3NPMGo0WjJaZmJLCi8xMlhxUGE0VjdxenIvMVc1VTVac3FUaVlVZWN0Rk5zTWMyTWxJK0dFWXI3U2NNS3B2SzNYSUF0bHprNk9GVXkKcFFJREFRQUJvMll3WkRBT0JnTlZIUThCQWY4RUJBTUNBUVl3RWdZRFZSMFRBUUgvQkFnd0JnRUIvd0lCQWpBZApCZ05WSFE0RUZnUVU2SnJmV3piM3c0cFNEQW9nWjZhazZIenlVVEV3SHdZRFZSMGpCQmd3Rm9BVTZKcmZXemIzCnc0cFNEQW9nWjZhazZIenlVVEV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUNZVGROOEx1ZGpnaEp3SWdXd2sKbmlPcDYvbENiRXJFQklMcE5OWHVUMTc5Sk4vUEppSUN2RmdOd3JzNDltOHY3S015UjVuSVhmTXpqdDliSVgzOApDeEhrQ0E3SnNtNExJTWhSbFBGMUo2ZjVJWG5LWDQ5YXNpb0wvK1Z6c0luVzJTTlo3aWRUZldTbmNlbkxQalZBCmErc0ZZRU1Fa25NbkxPK3JON3A4Z1NnN1hjWnN3Nmc5ajBJS1pvRVNWajdvbjFITU5oNThoTTR3QjE4S2FlWFcKczlnSGh2aTNNQ0c3Z3ZKM2pwbEFHTGNmbkFzdGdocmlnRGJDRTAzTlBSV3dHWmtrVHQrcFJEK3dPeUlEVWFzdQptSnRZbHduUllGS1lIbWNvR3RzNnBNaVQ3WWxFYUg3UHBlSFdTYk92WFY0dDJwQ1gxdE01VysxdDNDK3BCTW5WClJRRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
metadata:
  name: cluster-info
  namespace: cluster-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ksonnet.io/component: kubeconfig
  name: kubeconfig
  namespace: cluster-operator
spec:
  ports:
  - port: 8085
    targetPort: 8085
  selector:
    app: kubeconfig
  type: ClusterIP
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    ksonnet.io/component: kubeconfig
  name: kubeconfig
  namespace: cluster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeconfig
  template:
    metadata:
      labels:
        app: kubeconfig
    spec:
      serviceAccountName: cluster-operator
      containers:
      - image: asdfsx/kubeconfig
        name: kubeconfig
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: cluster-info
