
apiVersion: v1
kind: ConfigMap
data:
  CLUSTER_SERVER: https://172.17.255.240:8443
  CLUSTER_CA_DATA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ3akNDQXRhZ0F3SUJBZ0lVQ3JnbUlrN1crbXE5V0NQcjFMaDgrK2ZHckE0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2ZURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFXcHBibWN4RlRBVEJnTlZCQWNUREVKbAphV3BwYm1jZ1kybDBlVEVUTUJFR0ExVUVDaE1LUzNWaVpYSnVaWFJsY3pFYk1Ca0dBMVVFQ3hNU1MzVmlaWEp1ClpYUmxjeTFoYm5OcFlteGxNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6TUI0WERURTRNRGt5T0RFeE5EWXcKTUZvWERUSXpNRGt5TnpFeE5EWXdNRm93ZlRFTE1Ba0dBMVVFQmhNQ1EwNHhFREFPQmdOVkJBZ1RCMEpsYVdwcApibWN4RlRBVEJnTlZCQWNUREVKbGFXcHBibWNnWTJsMGVURVRNQkVHQTFVRUNoTUtTM1ZpWlhKdVpYUmxjekViCk1Ca0dBMVVFQ3hNU1MzVmlaWEp1WlhSbGN5MWhibk5wWW14bE1STXdFUVlEVlFRREV3cHJkV0psY201bGRHVnoKTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3dkRBaFlJS3pHQzMxT1BZdGZtRworUDdTRjhHeEdveFYvVWliZ1MwSXljWHZMRXRnaTBWMEdwdjYvdHVEL3JncWdsbkxEZWppTUJHc0RHMUJBb0Y2CnZoSnVhTk1rUFlqcStaUWY5Rzl0OEhFRHdSKzFGQ3ZrQUdDTytJZ3ZSY2tPdThBNkMrRWJSNkkzVDRaYVl0VlcKRW9DSkY0YzBSMTVXeUY4TGpzZzlGbVF0cEQ0UHBsNDlpZjR5L0luWUIwem1pUnpENE9DV2VYWFFNbEp0OU11WQo5YzRZd3hRcW4rR2x0amdScDNNeHRQT09XdHVoUXlickI0cFNma2E4NHBGVmdxdDRkTTA3SDRCMVprUG5rS0wzCitMQzdTWHFTU294dXhVY2V6Nms2RFZIYzZndGtnL2gvRDZibHo5YWtiR3llR0FpZ1ZVeGNiN1B6NXhsY04zUHMKSHdJREFRQUJvMll3WkRBT0JnTlZIUThCQWY4RUJBTUNBUVl3RWdZRFZSMFRBUUgvQkFnd0JnRUIvd0lCQWpBZApCZ05WSFE0RUZnUVVNczdKandFNloyTGEzVFgxNVhiZnhzbVVDNG93SHdZRFZSMGpCQmd3Rm9BVU1zN0pqd0U2CloyTGEzVFgxNVhiZnhzbVVDNG93RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUZoZ3k5aWpaT3ZUWjU4NDh2OHMKYVFybnJEMEozY1ZJby91U21xQXY4N3c4eGJ6NWw2QTVYUjJCejFDUVkwcTlFcEZWNm45YzF5aUZBbXB5T2lOVQp1WElzYVVBOUt6U3l4ZzArVU9ObDc3M1QvTm4vS3RiVW01STVPNVZIVURuQkNRUWsyS3Jjc00rTGl0RXZZREJQCklXaUZRcFVPWnpJbWJnc3drWk1EYzAwT21NckdtN3ZPZTJQMjZJTUNrTHhrZTkrUEhxWEVKYWYxNGM2WjMraXIKN0hscHdRZnM0bUErYXlJR0Z2Qys3Ylg1VXJicWsyQUxVRkF2OXJBTkVXbEQ3RGlTWk9RZ05DQ1FZYzN2U3JXYwpubEJDNjBhNkhNUXJ6alFVTDlLY3FBN3kxNEdxcXdoM09MWmR1cm16ZlltYmpzMzhuSWMxZkFyd2JsOE83V25QCnJibz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  TILLER_ROLE: tiller-user
  TILLER_NAMESPACE: kube-system
  NAMESPACE_PREFIX: clustar-
metadata:
  name: cluster-info
  namespace: cluster-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ksonnet.io/component: kubeconfig
  name: kubeconfig
  namespace: cluster-operator
spec:
  ports:
  - port: 8085
    targetPort: 8085
  selector:
    app: kubeconfig
  type: ClusterIP
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    ksonnet.io/component: kubeconfig
  name: kubeconfig
  namespace: cluster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeconfig
  template:
    metadata:
      labels:
        app: kubeconfig
    spec:
      serviceAccountName: cluster-operator
      containers:
      - image: asdfsx/kubeconfig
        name: kubeconfig
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: cluster-info
