apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeconfig
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: workshop
spec:
  rules:
  - host: kubeconfig.hongkong.ai
    http:
      paths:
      - path: /
        backend:
          serviceName: kubeconfig
          servicePort: 8085
